name: Nx Affected Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow push (tags, commits)
      pull-requests: write
      id-token: write # needed for provenance data generation

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: npx nx run-many -t=build && npx nx run-many -t=lint

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run affected release
        run: |
          npm config set //registry.npmjs.org/:_authToken "${{ secrets.NODE_AUTH_TOKEN }}"
          npm_config_legacy_peer_deps=false npx nx release --yes
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
